<?xml version="1.0" encoding="utf-8"?><Database Name="Kartel" EntityNamespace="Kartel.Domain.Entities" ContextNamespace="Kartel.Domain.DAL" Class="KartelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.UserPhones" Member="UserPhones">
    <Type Name="UserPhone">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="User_UserPhone" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserOccupationInfo" Member="UserOccupationInfos">
    <Type Name="UserOccupationInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Importer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OEM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Whoseller" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Exporter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ODM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SingleSeller" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Developer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Agent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Distributor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_UserOccupationInfo" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Subdomain" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LogoUrl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIO" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FIOImg" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Skype" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ICQ" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ZIP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ListWork" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="People" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Capital" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Money" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="About" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mainproduct" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Geography" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Certificates" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="License" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dealer" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CertificateCompany" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CertificateCountry" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CertificateAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CertificateDirector" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CertificateNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CertificateInn" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CertificateDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CertificateOpf" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CartificateU" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CertificateCapital" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Tarif" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TariffExpiration" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TariffMoney" Type="System.Data.Linq.Binary" DbType="VarBinary(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TariffTmp" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Activate" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ConfigSave2Week" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoggedIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoggedDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Administrator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Design" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ListCertificate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BannerPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="User_UserPhone" Member="UserPhones" ThisKey="Id" OtherKey="UserId" Type="UserPhone" />
      <Association Name="User_UserOccupationInfo" Member="UserOccupationInfos" ThisKey="Id" OtherKey="UserId" Type="UserOccupationInfo" Cardinality="One" />
      <Association Name="User_UserLegalInfo" Member="UserLegalInfos" ThisKey="Id" OtherKey="UserId" Type="UserLegalInfo" Cardinality="One" />
      <Association Name="User_UserCategory" Member="UserCategories" ThisKey="Id" OtherKey="UserId" Type="UserCategory" />
      <Association Name="User_Product" Member="Products" ThisKey="Id" OtherKey="UserId" Type="Product" />
      <Association Name="User_Tender" Member="Tenders" ThisKey="Id" OtherKey="UserId" Type="Tender" />
      <Association Name="User_TenderOffer" Member="TenderOffers" ThisKey="Id" OtherKey="UserId" Type="TenderOffer" />
    </Type>
  </Table>
  <Table Name="dbo.UserLegalInfo" Member="UserLegalInfos">
    <Type Name="UserLegalInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OGRN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KPP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountRNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountKNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountBank" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccountBankBIK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="User_UserLegalInfo" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TendersCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ViewMode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Category" Member="ChildCategories" ThisKey="Id" OtherKey="ParentId" Type="Category" />
      <Association Name="Category_Product" Member="Products" ThisKey="Id" OtherKey="CategoryId" Type="Product" />
      <Association Name="Category_Tender" Member="Tenders" ThisKey="Id" OtherKey="CategoryId" Type="Tender" />
      <Association Name="Category_CategoryMapItem" Member="CategoryMapItems" ThisKey="Id" OtherKey="CategoryId" Type="CategoryMapItem" />
      <Association Name="Category_CategoryMap" Member="CategoryMaps" ThisKey="Id" OtherKey="CategoryId" Type="CategoryMap" Cardinality="One" />
      <Association Name="Category_Category" Member="ParentCategory" ThisKey="ParentId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserCategories" Member="UserCategories">
    <Type Name="UserCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserCategory_Product" Member="Products" ThisKey="Id" OtherKey="UserCategoryId" Type="Product" />
      <Association Name="User_UserCategory" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductImages" Member="ProductImages">
    <Type Name="ProductImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductImage" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Field1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field4" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field5" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field6" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field8" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Field9" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Measure" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MinimunLotSize" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MinimumLotMeasure" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="VendorCountry" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeliveryTime" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeliveryPossibilityDay" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeliveryPossibilityMeasure" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeliveryPossibilityTime" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ProductBox" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Product_ProductImage" Member="ProductImages" ThisKey="Id" OtherKey="ProductId" Type="ProductImage" />
      <Association Name="Product_HotProduct" Member="HotProducts" ThisKey="Id" OtherKey="ProductId" Type="HotProduct" Cardinality="One" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserCategory_Product" Member="UserCategory" ThisKey="UserCategoryId" OtherKey="Id" Type="UserCategory" IsForeignKey="true" DeleteRule="SET DEFAULT" />
      <Association Name="User_Product" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotProducts" Member="HotProducts">
    <Type Name="HotProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnableHotProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PayedViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Clicks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_HotProduct" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tenders" Member="Tenders">
    <Type Name="Tender">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MinPrice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaxPrice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Measure" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Period" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tender_TenderOffer" Member="TenderOffers" ThisKey="Id" OtherKey="TenderId" Type="TenderOffer" />
      <Association Name="Category_Tender" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="User_Tender" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenderOffers" Member="TenderOffers">
    <Type Name="TenderOffer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryInfo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryOtherInfo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PaymentInfo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentOtherInfo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OfferText" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tender_TenderOffer" Member="Tender" ThisKey="TenderId" OtherKey="Id" Type="Tender" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_TenderOffer" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaticPages" Member="StaticPages">
    <Type Name="StaticPage">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Route" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banners" Member="Banners">
    <Type Name="Banner">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Html" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Href" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Objects" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Categories" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Extra" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailNotificationMessages" Member="MailNotificationMessages">
    <Type Name="MailNotificationMessage">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Recipient" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateEnqued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateSended" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryMapItems" Member="CategoryMapItems">
    <Type Name="CategoryMapItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryMapId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryMapItem" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="CategoryMap_CategoryMapItem" Member="CategoryMap" ThisKey="CategoryMapId" OtherKey="Id" Type="CategoryMap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryMaps" Member="CategoryMaps">
    <Type Name="CategoryMap">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CategoryMap_CategoryMapItem" Member="CategoryMapItems" ThisKey="Id" OtherKey="CategoryMapId" Type="CategoryMapItem" />
      <Association Name="Category_CategoryMap" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>