#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartel.Domain.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Kartel")]
	public partial class KartelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserPhone(Kartel.Domain.Entities.UserPhone instance);
    partial void UpdateUserPhone(Kartel.Domain.Entities.UserPhone instance);
    partial void DeleteUserPhone(Kartel.Domain.Entities.UserPhone instance);
    partial void InsertUserOccupationInfo(Kartel.Domain.Entities.UserOccupationInfo instance);
    partial void UpdateUserOccupationInfo(Kartel.Domain.Entities.UserOccupationInfo instance);
    partial void DeleteUserOccupationInfo(Kartel.Domain.Entities.UserOccupationInfo instance);
    partial void InsertUser(Kartel.Domain.Entities.User instance);
    partial void UpdateUser(Kartel.Domain.Entities.User instance);
    partial void DeleteUser(Kartel.Domain.Entities.User instance);
    partial void InsertUserLegalInfo(Kartel.Domain.Entities.UserLegalInfo instance);
    partial void UpdateUserLegalInfo(Kartel.Domain.Entities.UserLegalInfo instance);
    partial void DeleteUserLegalInfo(Kartel.Domain.Entities.UserLegalInfo instance);
    partial void InsertCategory(Kartel.Domain.Entities.Category instance);
    partial void UpdateCategory(Kartel.Domain.Entities.Category instance);
    partial void DeleteCategory(Kartel.Domain.Entities.Category instance);
    partial void InsertUserCategory(Kartel.Domain.Entities.UserCategory instance);
    partial void UpdateUserCategory(Kartel.Domain.Entities.UserCategory instance);
    partial void DeleteUserCategory(Kartel.Domain.Entities.UserCategory instance);
    partial void InsertProduct(Kartel.Domain.Entities.Product instance);
    partial void UpdateProduct(Kartel.Domain.Entities.Product instance);
    partial void DeleteProduct(Kartel.Domain.Entities.Product instance);
    #endregion
		
		public KartelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KartelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KartelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KartelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.UserPhone> UserPhones
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.UserPhone>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.UserOccupationInfo> UserOccupationInfos
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.UserOccupationInfo>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.User> Users
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.User>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.UserLegalInfo> UserLegalInfos
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.UserLegalInfo>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.Category> Categories
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.Category>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.UserCategory> UserCategories
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.UserCategory>();
			}
		}
		
		public System.Data.Linq.Table<Kartel.Domain.Entities.Product> Products
		{
			get
			{
				return this.GetTable<Kartel.Domain.Entities.Product>();
			}
		}
	}
}
namespace Kartel.Domain.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserPhones")]
	public partial class UserPhone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private string _CountryCode;
		
		private string _CityCode;
		
		private string _PhoneNumber;
		
		private short _Type;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnCityCodeChanging(string value);
    partial void OnCityCodeChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnTypeChanging(short value);
    partial void OnTypeChanged();
    #endregion
		
		public UserPhone()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="NVarChar(5)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="NVarChar(10)")]
		public string CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="SmallInt NOT NULL")]
		public short Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserPhone", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserPhones.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserPhones.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserOccupationInfo")]
	public partial class UserOccupationInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private bool _Importer;
		
		private bool _OEM;
		
		private bool _Whoseller;
		
		private bool _Exporter;
		
		private bool _ODM;
		
		private bool _SingleSeller;
		
		private bool _Developer;
		
		private bool _Agent;
		
		private bool _Distributor;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnImporterChanging(bool value);
    partial void OnImporterChanged();
    partial void OnOEMChanging(bool value);
    partial void OnOEMChanged();
    partial void OnWhosellerChanging(bool value);
    partial void OnWhosellerChanged();
    partial void OnExporterChanging(bool value);
    partial void OnExporterChanged();
    partial void OnODMChanging(bool value);
    partial void OnODMChanged();
    partial void OnSingleSellerChanging(bool value);
    partial void OnSingleSellerChanged();
    partial void OnDeveloperChanging(bool value);
    partial void OnDeveloperChanged();
    partial void OnAgentChanging(bool value);
    partial void OnAgentChanged();
    partial void OnDistributorChanging(bool value);
    partial void OnDistributorChanged();
    #endregion
		
		public UserOccupationInfo()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importer", DbType="Bit NOT NULL")]
		public bool Importer
		{
			get
			{
				return this._Importer;
			}
			set
			{
				if ((this._Importer != value))
				{
					this.OnImporterChanging(value);
					this.SendPropertyChanging();
					this._Importer = value;
					this.SendPropertyChanged("Importer");
					this.OnImporterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OEM", DbType="Bit NOT NULL")]
		public bool OEM
		{
			get
			{
				return this._OEM;
			}
			set
			{
				if ((this._OEM != value))
				{
					this.OnOEMChanging(value);
					this.SendPropertyChanging();
					this._OEM = value;
					this.SendPropertyChanged("OEM");
					this.OnOEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Whoseller", DbType="Bit NOT NULL")]
		public bool Whoseller
		{
			get
			{
				return this._Whoseller;
			}
			set
			{
				if ((this._Whoseller != value))
				{
					this.OnWhosellerChanging(value);
					this.SendPropertyChanging();
					this._Whoseller = value;
					this.SendPropertyChanged("Whoseller");
					this.OnWhosellerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exporter", DbType="Bit NOT NULL")]
		public bool Exporter
		{
			get
			{
				return this._Exporter;
			}
			set
			{
				if ((this._Exporter != value))
				{
					this.OnExporterChanging(value);
					this.SendPropertyChanging();
					this._Exporter = value;
					this.SendPropertyChanged("Exporter");
					this.OnExporterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ODM", DbType="Bit NOT NULL")]
		public bool ODM
		{
			get
			{
				return this._ODM;
			}
			set
			{
				if ((this._ODM != value))
				{
					this.OnODMChanging(value);
					this.SendPropertyChanging();
					this._ODM = value;
					this.SendPropertyChanged("ODM");
					this.OnODMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleSeller", DbType="Bit NOT NULL")]
		public bool SingleSeller
		{
			get
			{
				return this._SingleSeller;
			}
			set
			{
				if ((this._SingleSeller != value))
				{
					this.OnSingleSellerChanging(value);
					this.SendPropertyChanging();
					this._SingleSeller = value;
					this.SendPropertyChanged("SingleSeller");
					this.OnSingleSellerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Developer", DbType="Bit NOT NULL")]
		public bool Developer
		{
			get
			{
				return this._Developer;
			}
			set
			{
				if ((this._Developer != value))
				{
					this.OnDeveloperChanging(value);
					this.SendPropertyChanging();
					this._Developer = value;
					this.SendPropertyChanged("Developer");
					this.OnDeveloperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent", DbType="Bit NOT NULL")]
		public bool Agent
		{
			get
			{
				return this._Agent;
			}
			set
			{
				if ((this._Agent != value))
				{
					this.OnAgentChanging(value);
					this.SendPropertyChanging();
					this._Agent = value;
					this.SendPropertyChanged("Agent");
					this.OnAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distributor", DbType="Bit NOT NULL")]
		public bool Distributor
		{
			get
			{
				return this._Distributor;
			}
			set
			{
				if ((this._Distributor != value))
				{
					this.OnDistributorChanging(value);
					this.SendPropertyChanging();
					this._Distributor = value;
					this.SendPropertyChanged("Distributor");
					this.OnDistributorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserOccupationInfo", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserOccupationInfos = null;
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserOccupationInfos = this;
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Login;
		
		private string _PasswordHash;
		
		private string _Subdomain;
		
		private string _Company;
		
		private string _Brand;
		
		private string _LogoUrl;
		
		private string _FIO;
		
		private string _FIOImg;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Email;
		
		private string _CellPhone;
		
		private string _Skype;
		
		private string _ICQ;
		
		private string _Url;
		
		private string _Country;
		
		private string _Region;
		
		private string _City;
		
		private string _Address;
		
		private string _ZIP;
		
		private string _ListWork;
		
		private string _People;
		
		private string _Capital;
		
		private string _Money;
		
		private string _About;
		
		private string _Mainproduct;
		
		private string _Geography;
		
		private string _Certificates;
		
		private string _License;
		
		private string _Dealer;
		
		private string _CertificateCompany;
		
		private string _CertificateCountry;
		
		private string _CertificateAddress;
		
		private string _CertificateDirector;
		
		private string _CertificateNumber;
		
		private string _CertificateInn;
		
		private string _CertificateDate;
		
		private string _CertificateOpf;
		
		private string _CartificateU;
		
		private string _CertificateCapital;
		
		private string _Tarif;
		
		private System.Nullable<System.DateTime> _TariffExpiration;
		
		private System.Data.Linq.Binary _TariffMoney;
		
		private string _TariffTmp;
		
		private string _Activate;
		
		private int _ConfigSave2Week;
		
		private string _LoggedIP;
		
		private System.Nullable<System.DateTime> _LoggedDate;
		
		private int _Administrator;
		
		private System.DateTime _Date;
		
		private string _Design;
		
		private string _ListCertificate;
		
		private int _BannerPeriod;
		
		private string _PostCode;
		
		private EntitySet<UserPhone> _UserPhones;
		
		private EntityRef<UserOccupationInfo> _UserOccupationInfos;
		
		private EntityRef<UserLegalInfo> _UserLegalInfos;
		
		private EntitySet<UserCategory> _UserCategories;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnSubdomainChanging(string value);
    partial void OnSubdomainChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnBrandChanging(string value);
    partial void OnBrandChanged();
    partial void OnLogoUrlChanging(string value);
    partial void OnLogoUrlChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnFIOImgChanging(string value);
    partial void OnFIOImgChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnICQChanging(string value);
    partial void OnICQChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnZIPChanging(string value);
    partial void OnZIPChanged();
    partial void OnListWorkChanging(string value);
    partial void OnListWorkChanged();
    partial void OnPeopleChanging(string value);
    partial void OnPeopleChanged();
    partial void OnCapitalChanging(string value);
    partial void OnCapitalChanged();
    partial void OnMoneyChanging(string value);
    partial void OnMoneyChanged();
    partial void OnAboutChanging(string value);
    partial void OnAboutChanged();
    partial void OnMainproductChanging(string value);
    partial void OnMainproductChanged();
    partial void OnGeographyChanging(string value);
    partial void OnGeographyChanged();
    partial void OnCertificatesChanging(string value);
    partial void OnCertificatesChanged();
    partial void OnLicenseChanging(string value);
    partial void OnLicenseChanged();
    partial void OnDealerChanging(string value);
    partial void OnDealerChanged();
    partial void OnCertificateCompanyChanging(string value);
    partial void OnCertificateCompanyChanged();
    partial void OnCertificateCountryChanging(string value);
    partial void OnCertificateCountryChanged();
    partial void OnCertificateAddressChanging(string value);
    partial void OnCertificateAddressChanged();
    partial void OnCertificateDirectorChanging(string value);
    partial void OnCertificateDirectorChanged();
    partial void OnCertificateNumberChanging(string value);
    partial void OnCertificateNumberChanged();
    partial void OnCertificateInnChanging(string value);
    partial void OnCertificateInnChanged();
    partial void OnCertificateDateChanging(string value);
    partial void OnCertificateDateChanged();
    partial void OnCertificateOpfChanging(string value);
    partial void OnCertificateOpfChanged();
    partial void OnCartificateUChanging(string value);
    partial void OnCartificateUChanged();
    partial void OnCertificateCapitalChanging(string value);
    partial void OnCertificateCapitalChanged();
    partial void OnTarifChanging(string value);
    partial void OnTarifChanged();
    partial void OnTariffExpirationChanging(System.Nullable<System.DateTime> value);
    partial void OnTariffExpirationChanged();
    partial void OnTariffMoneyChanging(System.Data.Linq.Binary value);
    partial void OnTariffMoneyChanged();
    partial void OnTariffTmpChanging(string value);
    partial void OnTariffTmpChanged();
    partial void OnActivateChanging(string value);
    partial void OnActivateChanged();
    partial void OnConfigSave2WeekChanging(int value);
    partial void OnConfigSave2WeekChanged();
    partial void OnLoggedIPChanging(string value);
    partial void OnLoggedIPChanged();
    partial void OnLoggedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoggedDateChanged();
    partial void OnAdministratorChanging(int value);
    partial void OnAdministratorChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnDesignChanging(string value);
    partial void OnDesignChanged();
    partial void OnListCertificateChanging(string value);
    partial void OnListCertificateChanged();
    partial void OnBannerPeriodChanging(int value);
    partial void OnBannerPeriodChanged();
    partial void OnPostCodeChanging(string value);
    partial void OnPostCodeChanged();
    #endregion
		
		public User()
		{
			this._UserPhones = new EntitySet<UserPhone>(new Action<UserPhone>(this.attach_UserPhones), new Action<UserPhone>(this.detach_UserPhones));
			this._UserOccupationInfos = default(EntityRef<UserOccupationInfo>);
			this._UserLegalInfos = default(EntityRef<UserLegalInfo>);
			this._UserCategories = new EntitySet<UserCategory>(new Action<UserCategory>(this.attach_UserCategories), new Action<UserCategory>(this.detach_UserCategories));
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subdomain", DbType="VarChar(255)")]
		public string Subdomain
		{
			get
			{
				return this._Subdomain;
			}
			set
			{
				if ((this._Subdomain != value))
				{
					this.OnSubdomainChanging(value);
					this.SendPropertyChanging();
					this._Subdomain = value;
					this.SendPropertyChanged("Subdomain");
					this.OnSubdomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(255)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this.OnBrandChanging(value);
					this.SendPropertyChanging();
					this._Brand = value;
					this.SendPropertyChanged("Brand");
					this.OnBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoUrl", DbType="VarChar(50)")]
		public string LogoUrl
		{
			get
			{
				return this._LogoUrl;
			}
			set
			{
				if ((this._LogoUrl != value))
				{
					this.OnLogoUrlChanging(value);
					this.SendPropertyChanging();
					this._LogoUrl = value;
					this.SendPropertyChanged("LogoUrl");
					this.OnLogoUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="VarChar(255)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIOImg", DbType="VarChar(50)")]
		public string FIOImg
		{
			get
			{
				return this._FIOImg;
			}
			set
			{
				if ((this._FIOImg != value))
				{
					this.OnFIOImgChanging(value);
					this.SendPropertyChanging();
					this._FIOImg = value;
					this.SendPropertyChanged("FIOImg");
					this.OnFIOImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(200)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(200)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="VarChar(20)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="VarChar(100)")]
		public string Skype
		{
			get
			{
				return this._Skype;
			}
			set
			{
				if ((this._Skype != value))
				{
					this.OnSkypeChanging(value);
					this.SendPropertyChanging();
					this._Skype = value;
					this.SendPropertyChanged("Skype");
					this.OnSkypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICQ", DbType="VarChar(10)")]
		public string ICQ
		{
			get
			{
				return this._ICQ;
			}
			set
			{
				if ((this._ICQ != value))
				{
					this.OnICQChanging(value);
					this.SendPropertyChanging();
					this._ICQ = value;
					this.SendPropertyChanged("ICQ");
					this.OnICQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(100)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="VarChar(50)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="VarChar(10)")]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this.OnZIPChanging(value);
					this.SendPropertyChanging();
					this._ZIP = value;
					this.SendPropertyChanged("ZIP");
					this.OnZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListWork", DbType="VarChar(255)")]
		public string ListWork
		{
			get
			{
				return this._ListWork;
			}
			set
			{
				if ((this._ListWork != value))
				{
					this.OnListWorkChanging(value);
					this.SendPropertyChanging();
					this._ListWork = value;
					this.SendPropertyChanged("ListWork");
					this.OnListWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_People", DbType="VarChar(255)")]
		public string People
		{
			get
			{
				return this._People;
			}
			set
			{
				if ((this._People != value))
				{
					this.OnPeopleChanging(value);
					this.SendPropertyChanging();
					this._People = value;
					this.SendPropertyChanged("People");
					this.OnPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="VarChar(255)")]
		public string Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="VarChar(255)")]
		public string Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_About", DbType="VarChar(MAX)")]
		public string About
		{
			get
			{
				return this._About;
			}
			set
			{
				if ((this._About != value))
				{
					this.OnAboutChanging(value);
					this.SendPropertyChanging();
					this._About = value;
					this.SendPropertyChanged("About");
					this.OnAboutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mainproduct", DbType="VarChar(MAX)")]
		public string Mainproduct
		{
			get
			{
				return this._Mainproduct;
			}
			set
			{
				if ((this._Mainproduct != value))
				{
					this.OnMainproductChanging(value);
					this.SendPropertyChanging();
					this._Mainproduct = value;
					this.SendPropertyChanged("Mainproduct");
					this.OnMainproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geography", DbType="VarChar(MAX)")]
		public string Geography
		{
			get
			{
				return this._Geography;
			}
			set
			{
				if ((this._Geography != value))
				{
					this.OnGeographyChanging(value);
					this.SendPropertyChanging();
					this._Geography = value;
					this.SendPropertyChanged("Geography");
					this.OnGeographyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certificates", DbType="VarChar(MAX)")]
		public string Certificates
		{
			get
			{
				return this._Certificates;
			}
			set
			{
				if ((this._Certificates != value))
				{
					this.OnCertificatesChanging(value);
					this.SendPropertyChanging();
					this._Certificates = value;
					this.SendPropertyChanged("Certificates");
					this.OnCertificatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_License", DbType="VarChar(MAX)")]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this.OnLicenseChanging(value);
					this.SendPropertyChanging();
					this._License = value;
					this.SendPropertyChanged("License");
					this.OnLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dealer", DbType="VarChar(MAX)")]
		public string Dealer
		{
			get
			{
				return this._Dealer;
			}
			set
			{
				if ((this._Dealer != value))
				{
					this.OnDealerChanging(value);
					this.SendPropertyChanging();
					this._Dealer = value;
					this.SendPropertyChanged("Dealer");
					this.OnDealerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateCompany", DbType="VarChar(100)")]
		public string CertificateCompany
		{
			get
			{
				return this._CertificateCompany;
			}
			set
			{
				if ((this._CertificateCompany != value))
				{
					this.OnCertificateCompanyChanging(value);
					this.SendPropertyChanging();
					this._CertificateCompany = value;
					this.SendPropertyChanged("CertificateCompany");
					this.OnCertificateCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateCountry", DbType="VarChar(100)")]
		public string CertificateCountry
		{
			get
			{
				return this._CertificateCountry;
			}
			set
			{
				if ((this._CertificateCountry != value))
				{
					this.OnCertificateCountryChanging(value);
					this.SendPropertyChanging();
					this._CertificateCountry = value;
					this.SendPropertyChanged("CertificateCountry");
					this.OnCertificateCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateAddress", DbType="VarChar(255)")]
		public string CertificateAddress
		{
			get
			{
				return this._CertificateAddress;
			}
			set
			{
				if ((this._CertificateAddress != value))
				{
					this.OnCertificateAddressChanging(value);
					this.SendPropertyChanging();
					this._CertificateAddress = value;
					this.SendPropertyChanged("CertificateAddress");
					this.OnCertificateAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateDirector", DbType="VarChar(100)")]
		public string CertificateDirector
		{
			get
			{
				return this._CertificateDirector;
			}
			set
			{
				if ((this._CertificateDirector != value))
				{
					this.OnCertificateDirectorChanging(value);
					this.SendPropertyChanging();
					this._CertificateDirector = value;
					this.SendPropertyChanged("CertificateDirector");
					this.OnCertificateDirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateNumber", DbType="VarChar(50)")]
		public string CertificateNumber
		{
			get
			{
				return this._CertificateNumber;
			}
			set
			{
				if ((this._CertificateNumber != value))
				{
					this.OnCertificateNumberChanging(value);
					this.SendPropertyChanging();
					this._CertificateNumber = value;
					this.SendPropertyChanged("CertificateNumber");
					this.OnCertificateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateInn", DbType="VarChar(25)")]
		public string CertificateInn
		{
			get
			{
				return this._CertificateInn;
			}
			set
			{
				if ((this._CertificateInn != value))
				{
					this.OnCertificateInnChanging(value);
					this.SendPropertyChanging();
					this._CertificateInn = value;
					this.SendPropertyChanged("CertificateInn");
					this.OnCertificateInnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateDate", DbType="VarChar(255)")]
		public string CertificateDate
		{
			get
			{
				return this._CertificateDate;
			}
			set
			{
				if ((this._CertificateDate != value))
				{
					this.OnCertificateDateChanging(value);
					this.SendPropertyChanging();
					this._CertificateDate = value;
					this.SendPropertyChanged("CertificateDate");
					this.OnCertificateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateOpf", DbType="VarChar(255)")]
		public string CertificateOpf
		{
			get
			{
				return this._CertificateOpf;
			}
			set
			{
				if ((this._CertificateOpf != value))
				{
					this.OnCertificateOpfChanging(value);
					this.SendPropertyChanging();
					this._CertificateOpf = value;
					this.SendPropertyChanged("CertificateOpf");
					this.OnCertificateOpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CartificateU", DbType="VarChar(255)")]
		public string CartificateU
		{
			get
			{
				return this._CartificateU;
			}
			set
			{
				if ((this._CartificateU != value))
				{
					this.OnCartificateUChanging(value);
					this.SendPropertyChanging();
					this._CartificateU = value;
					this.SendPropertyChanged("CartificateU");
					this.OnCartificateUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificateCapital", DbType="VarChar(255)")]
		public string CertificateCapital
		{
			get
			{
				return this._CertificateCapital;
			}
			set
			{
				if ((this._CertificateCapital != value))
				{
					this.OnCertificateCapitalChanging(value);
					this.SendPropertyChanging();
					this._CertificateCapital = value;
					this.SendPropertyChanged("CertificateCapital");
					this.OnCertificateCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarif", DbType="VarChar(10)")]
		public string Tarif
		{
			get
			{
				return this._Tarif;
			}
			set
			{
				if ((this._Tarif != value))
				{
					this.OnTarifChanging(value);
					this.SendPropertyChanging();
					this._Tarif = value;
					this.SendPropertyChanged("Tarif");
					this.OnTarifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TariffExpiration", DbType="Date")]
		public System.Nullable<System.DateTime> TariffExpiration
		{
			get
			{
				return this._TariffExpiration;
			}
			set
			{
				if ((this._TariffExpiration != value))
				{
					this.OnTariffExpirationChanging(value);
					this.SendPropertyChanging();
					this._TariffExpiration = value;
					this.SendPropertyChanged("TariffExpiration");
					this.OnTariffExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TariffMoney", DbType="VarBinary(255)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TariffMoney
		{
			get
			{
				return this._TariffMoney;
			}
			set
			{
				if ((this._TariffMoney != value))
				{
					this.OnTariffMoneyChanging(value);
					this.SendPropertyChanging();
					this._TariffMoney = value;
					this.SendPropertyChanged("TariffMoney");
					this.OnTariffMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TariffTmp", DbType="VarChar(25)")]
		public string TariffTmp
		{
			get
			{
				return this._TariffTmp;
			}
			set
			{
				if ((this._TariffTmp != value))
				{
					this.OnTariffTmpChanging(value);
					this.SendPropertyChanging();
					this._TariffTmp = value;
					this.SendPropertyChanged("TariffTmp");
					this.OnTariffTmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activate", DbType="VarChar(32)")]
		public string Activate
		{
			get
			{
				return this._Activate;
			}
			set
			{
				if ((this._Activate != value))
				{
					this.OnActivateChanging(value);
					this.SendPropertyChanging();
					this._Activate = value;
					this.SendPropertyChanged("Activate");
					this.OnActivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfigSave2Week", DbType="Int NOT NULL")]
		public int ConfigSave2Week
		{
			get
			{
				return this._ConfigSave2Week;
			}
			set
			{
				if ((this._ConfigSave2Week != value))
				{
					this.OnConfigSave2WeekChanging(value);
					this.SendPropertyChanging();
					this._ConfigSave2Week = value;
					this.SendPropertyChanged("ConfigSave2Week");
					this.OnConfigSave2WeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedIP", DbType="VarChar(15)")]
		public string LoggedIP
		{
			get
			{
				return this._LoggedIP;
			}
			set
			{
				if ((this._LoggedIP != value))
				{
					this.OnLoggedIPChanging(value);
					this.SendPropertyChanging();
					this._LoggedIP = value;
					this.SendPropertyChanged("LoggedIP");
					this.OnLoggedIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LoggedDate
		{
			get
			{
				return this._LoggedDate;
			}
			set
			{
				if ((this._LoggedDate != value))
				{
					this.OnLoggedDateChanging(value);
					this.SendPropertyChanging();
					this._LoggedDate = value;
					this.SendPropertyChanged("LoggedDate");
					this.OnLoggedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrator", DbType="Int NOT NULL")]
		public int Administrator
		{
			get
			{
				return this._Administrator;
			}
			set
			{
				if ((this._Administrator != value))
				{
					this.OnAdministratorChanging(value);
					this.SendPropertyChanging();
					this._Administrator = value;
					this.SendPropertyChanged("Administrator");
					this.OnAdministratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime2 NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Design", DbType="VarChar(10)")]
		public string Design
		{
			get
			{
				return this._Design;
			}
			set
			{
				if ((this._Design != value))
				{
					this.OnDesignChanging(value);
					this.SendPropertyChanging();
					this._Design = value;
					this.SendPropertyChanged("Design");
					this.OnDesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListCertificate", DbType="VarChar(MAX)")]
		public string ListCertificate
		{
			get
			{
				return this._ListCertificate;
			}
			set
			{
				if ((this._ListCertificate != value))
				{
					this.OnListCertificateChanging(value);
					this.SendPropertyChanging();
					this._ListCertificate = value;
					this.SendPropertyChanged("ListCertificate");
					this.OnListCertificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BannerPeriod", DbType="Int NOT NULL")]
		public int BannerPeriod
		{
			get
			{
				return this._BannerPeriod;
			}
			set
			{
				if ((this._BannerPeriod != value))
				{
					this.OnBannerPeriodChanging(value);
					this.SendPropertyChanging();
					this._BannerPeriod = value;
					this.SendPropertyChanged("BannerPeriod");
					this.OnBannerPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="VarChar(255)")]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this.OnPostCodeChanging(value);
					this.SendPropertyChanging();
					this._PostCode = value;
					this.SendPropertyChanged("PostCode");
					this.OnPostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserPhone", Storage="_UserPhones", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<UserPhone> UserPhones
		{
			get
			{
				return this._UserPhones;
			}
			set
			{
				this._UserPhones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserOccupationInfo", Storage="_UserOccupationInfos", ThisKey="Id", OtherKey="UserId", IsUnique=true, IsForeignKey=false)]
		public UserOccupationInfo UserOccupationInfos
		{
			get
			{
				return this._UserOccupationInfos.Entity;
			}
			set
			{
				UserOccupationInfo previousValue = this._UserOccupationInfos.Entity;
				if (((previousValue != value) 
							|| (this._UserOccupationInfos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserOccupationInfos.Entity = null;
						previousValue.User = null;
					}
					this._UserOccupationInfos.Entity = value;
					if ((value != null))
					{
						value.User = this;
					}
					this.SendPropertyChanged("UserOccupationInfos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserLegalInfo", Storage="_UserLegalInfos", ThisKey="Id", OtherKey="UserId", IsUnique=true, IsForeignKey=false)]
		public UserLegalInfo UserLegalInfos
		{
			get
			{
				return this._UserLegalInfos.Entity;
			}
			set
			{
				UserLegalInfo previousValue = this._UserLegalInfos.Entity;
				if (((previousValue != value) 
							|| (this._UserLegalInfos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserLegalInfos.Entity = null;
						previousValue.User = null;
					}
					this._UserLegalInfos.Entity = value;
					if ((value != null))
					{
						value.User = this;
					}
					this.SendPropertyChanged("UserLegalInfos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserCategory", Storage="_UserCategories", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<UserCategory> UserCategories
		{
			get
			{
				return this._UserCategories;
			}
			set
			{
				this._UserCategories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Product", Storage="_Products", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserPhones(UserPhone entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UserPhones(UserPhone entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_UserCategories(UserCategory entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UserCategories(UserCategory entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLegalInfo")]
	public partial class UserLegalInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private string _OGRN;
		
		private string _INN;
		
		private string _KPP;
		
		private string _AccountRNumber;
		
		private string _AccountKNumber;
		
		private string _AccountBank;
		
		private string _AccountBankBIK;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnOGRNChanging(string value);
    partial void OnOGRNChanged();
    partial void OnINNChanging(string value);
    partial void OnINNChanged();
    partial void OnKPPChanging(string value);
    partial void OnKPPChanged();
    partial void OnAccountRNumberChanging(string value);
    partial void OnAccountRNumberChanged();
    partial void OnAccountKNumberChanging(string value);
    partial void OnAccountKNumberChanged();
    partial void OnAccountBankChanging(string value);
    partial void OnAccountBankChanged();
    partial void OnAccountBankBIKChanging(string value);
    partial void OnAccountBankBIKChanged();
    #endregion
		
		public UserLegalInfo()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGRN", DbType="NVarChar(50)")]
		public string OGRN
		{
			get
			{
				return this._OGRN;
			}
			set
			{
				if ((this._OGRN != value))
				{
					this.OnOGRNChanging(value);
					this.SendPropertyChanging();
					this._OGRN = value;
					this.SendPropertyChanged("OGRN");
					this.OnOGRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INN", DbType="VarChar(50)")]
		public string INN
		{
			get
			{
				return this._INN;
			}
			set
			{
				if ((this._INN != value))
				{
					this.OnINNChanging(value);
					this.SendPropertyChanging();
					this._INN = value;
					this.SendPropertyChanged("INN");
					this.OnINNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPP", DbType="VarChar(50)")]
		public string KPP
		{
			get
			{
				return this._KPP;
			}
			set
			{
				if ((this._KPP != value))
				{
					this.OnKPPChanging(value);
					this.SendPropertyChanging();
					this._KPP = value;
					this.SendPropertyChanged("KPP");
					this.OnKPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountRNumber", DbType="VarChar(50)")]
		public string AccountRNumber
		{
			get
			{
				return this._AccountRNumber;
			}
			set
			{
				if ((this._AccountRNumber != value))
				{
					this.OnAccountRNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountRNumber = value;
					this.SendPropertyChanged("AccountRNumber");
					this.OnAccountRNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountKNumber", DbType="VarChar(50)")]
		public string AccountKNumber
		{
			get
			{
				return this._AccountKNumber;
			}
			set
			{
				if ((this._AccountKNumber != value))
				{
					this.OnAccountKNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountKNumber = value;
					this.SendPropertyChanged("AccountKNumber");
					this.OnAccountKNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBank", DbType="NVarChar(255)")]
		public string AccountBank
		{
			get
			{
				return this._AccountBank;
			}
			set
			{
				if ((this._AccountBank != value))
				{
					this.OnAccountBankChanging(value);
					this.SendPropertyChanging();
					this._AccountBank = value;
					this.SendPropertyChanged("AccountBank");
					this.OnAccountBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBankBIK", DbType="NVarChar(50)")]
		public string AccountBankBIK
		{
			get
			{
				return this._AccountBankBIK;
			}
			set
			{
				if ((this._AccountBankBIK != value))
				{
					this.OnAccountBankBIKChanging(value);
					this.SendPropertyChanging();
					this._AccountBankBIK = value;
					this.SendPropertyChanged("AccountBankBIK");
					this.OnAccountBankBIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserLegalInfo", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserLegalInfos = null;
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserLegalInfos = this;
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ParentId;
		
		private string _Title;
		
		private int _ProductsCount;
		
		private int _TendersCount;
		
		private int _Sort;
		
		private int _ViewMode;
		
		private EntitySet<Category> _ChildCategories;
		
		private EntitySet<Product> _Products;
		
		private EntityRef<Category> _ParentCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnParentIdChanging(int value);
    partial void OnParentIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnProductsCountChanging(int value);
    partial void OnProductsCountChanged();
    partial void OnTendersCountChanging(int value);
    partial void OnTendersCountChanged();
    partial void OnSortChanging(int value);
    partial void OnSortChanged();
    partial void OnViewModeChanging(int value);
    partial void OnViewModeChanged();
    #endregion
		
		public Category()
		{
			this._ChildCategories = new EntitySet<Category>(new Action<Category>(this.attach_ChildCategories), new Action<Category>(this.detach_ChildCategories));
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			this._ParentCategory = default(EntityRef<Category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int NOT NULL")]
		public int ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					if (this._ParentCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductsCount", DbType="Int NOT NULL")]
		public int ProductsCount
		{
			get
			{
				return this._ProductsCount;
			}
			set
			{
				if ((this._ProductsCount != value))
				{
					this.OnProductsCountChanging(value);
					this.SendPropertyChanging();
					this._ProductsCount = value;
					this.SendPropertyChanged("ProductsCount");
					this.OnProductsCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TendersCount", DbType="Int NOT NULL")]
		public int TendersCount
		{
			get
			{
				return this._TendersCount;
			}
			set
			{
				if ((this._TendersCount != value))
				{
					this.OnTendersCountChanging(value);
					this.SendPropertyChanging();
					this._TendersCount = value;
					this.SendPropertyChanged("TendersCount");
					this.OnTendersCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewMode", DbType="Int NOT NULL")]
		public int ViewMode
		{
			get
			{
				return this._ViewMode;
			}
			set
			{
				if ((this._ViewMode != value))
				{
					this.OnViewModeChanging(value);
					this.SendPropertyChanging();
					this._ViewMode = value;
					this.SendPropertyChanged("ViewMode");
					this.OnViewModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Category", Storage="_ChildCategories", ThisKey="Id", OtherKey="ParentId")]
		public EntitySet<Category> ChildCategories
		{
			get
			{
				return this._ChildCategories;
			}
			set
			{
				this._ChildCategories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Products", ThisKey="Id", OtherKey="CategoryId")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Category", Storage="_ParentCategory", ThisKey="ParentId", OtherKey="Id", IsForeignKey=true)]
		public Category ParentCategory
		{
			get
			{
				return this._ParentCategory.Entity;
			}
			set
			{
				Category previousValue = this._ParentCategory.Entity;
				if (((previousValue != value) 
							|| (this._ParentCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ParentCategory.Entity = null;
						previousValue.ChildCategories.Remove(this);
					}
					this._ParentCategory.Entity = value;
					if ((value != null))
					{
						value.ChildCategories.Add(this);
						this._ParentId = value.Id;
					}
					else
					{
						this._ParentId = default(int);
					}
					this.SendPropertyChanged("ParentCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChildCategories(Category entity)
		{
			this.SendPropertyChanging();
			entity.ParentCategory = this;
		}
		
		private void detach_ChildCategories(Category entity)
		{
			this.SendPropertyChanging();
			entity.ParentCategory = null;
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserCategories")]
	public partial class UserCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private string _Title;
		
		private string _Description;
		
		private int _Position;
		
		private EntitySet<Product> _Products;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPositionChanging(int value);
    partial void OnPositionChanged();
    #endregion
		
		public UserCategory()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="Int NOT NULL")]
		public int Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserCategory_Product", Storage="_Products", ThisKey="Id", OtherKey="UserCategoryId")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserCategory", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserCategories.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserCategories.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.UserCategory = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.UserCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private int _CategoryId;
		
		private string _Title;
		
		private string _Keywords;
		
		private string _Description;
		
		private string _Img;
		
		private System.DateTime _Date;
		
		private string _Field1;
		
		private string _Field3;
		
		private string _Field4;
		
		private string _Field5;
		
		private string _Field6;
		
		private string _Field8;
		
		private string _Field9;
		
		private int _UserCategoryId;
		
		private EntityRef<Category> _Category;
		
		private EntityRef<UserCategory> _UserCategory;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnField1Changing(string value);
    partial void OnField1Changed();
    partial void OnField3Changing(string value);
    partial void OnField3Changed();
    partial void OnField4Changing(string value);
    partial void OnField4Changed();
    partial void OnField5Changing(string value);
    partial void OnField5Changed();
    partial void OnField6Changing(string value);
    partial void OnField6Changed();
    partial void OnField8Changing(string value);
    partial void OnField8Changed();
    partial void OnField9Changing(string value);
    partial void OnField9Changed();
    partial void OnUserCategoryIdChanging(int value);
    partial void OnUserCategoryIdChanged();
    #endregion
		
		public Product()
		{
			this._Category = default(EntityRef<Category>);
			this._UserCategory = default(EntityRef<UserCategory>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int NOT NULL")]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime2 NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field1", DbType="VarChar(255)")]
		public string Field1
		{
			get
			{
				return this._Field1;
			}
			set
			{
				if ((this._Field1 != value))
				{
					this.OnField1Changing(value);
					this.SendPropertyChanging();
					this._Field1 = value;
					this.SendPropertyChanged("Field1");
					this.OnField1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field3", DbType="VarChar(255)")]
		public string Field3
		{
			get
			{
				return this._Field3;
			}
			set
			{
				if ((this._Field3 != value))
				{
					this.OnField3Changing(value);
					this.SendPropertyChanging();
					this._Field3 = value;
					this.SendPropertyChanged("Field3");
					this.OnField3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field4", DbType="VarChar(255)")]
		public string Field4
		{
			get
			{
				return this._Field4;
			}
			set
			{
				if ((this._Field4 != value))
				{
					this.OnField4Changing(value);
					this.SendPropertyChanging();
					this._Field4 = value;
					this.SendPropertyChanged("Field4");
					this.OnField4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field5", DbType="VarChar(255)")]
		public string Field5
		{
			get
			{
				return this._Field5;
			}
			set
			{
				if ((this._Field5 != value))
				{
					this.OnField5Changing(value);
					this.SendPropertyChanging();
					this._Field5 = value;
					this.SendPropertyChanged("Field5");
					this.OnField5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field6", DbType="VarChar(255)")]
		public string Field6
		{
			get
			{
				return this._Field6;
			}
			set
			{
				if ((this._Field6 != value))
				{
					this.OnField6Changing(value);
					this.SendPropertyChanging();
					this._Field6 = value;
					this.SendPropertyChanged("Field6");
					this.OnField6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field8", DbType="VarChar(255)")]
		public string Field8
		{
			get
			{
				return this._Field8;
			}
			set
			{
				if ((this._Field8 != value))
				{
					this.OnField8Changing(value);
					this.SendPropertyChanging();
					this._Field8 = value;
					this.SendPropertyChanged("Field8");
					this.OnField8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field9", DbType="VarChar(255)")]
		public string Field9
		{
			get
			{
				return this._Field9;
			}
			set
			{
				if ((this._Field9 != value))
				{
					this.OnField9Changing(value);
					this.SendPropertyChanging();
					this._Field9 = value;
					this.SendPropertyChanged("Field9");
					this.OnField9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCategoryId", DbType="Int NOT NULL")]
		public int UserCategoryId
		{
			get
			{
				return this._UserCategoryId;
			}
			set
			{
				if ((this._UserCategoryId != value))
				{
					if (this._UserCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._UserCategoryId = value;
					this.SendPropertyChanged("UserCategoryId");
					this.OnUserCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Category", ThisKey="CategoryId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._CategoryId = value.Id;
					}
					else
					{
						this._CategoryId = default(int);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserCategory_Product", Storage="_UserCategory", ThisKey="UserCategoryId", OtherKey="Id", IsForeignKey=true)]
		public UserCategory UserCategory
		{
			get
			{
				return this._UserCategory.Entity;
			}
			set
			{
				UserCategory previousValue = this._UserCategory.Entity;
				if (((previousValue != value) 
							|| (this._UserCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserCategory.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._UserCategory.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._UserCategoryId = value.Id;
					}
					else
					{
						this._UserCategoryId = default(int);
					}
					this.SendPropertyChanged("UserCategory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Product", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
